# Generated by Django 4.1.5 on 2023-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_location',
            field=models.TextField(blank=True),
        ),
    ]
